# Generated by Django 5.2.17 on 2026-08-17 05:57

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('settings', '0004_alter_motel_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'base_manager_name': 'all_objects', 'ordering': ['kind', 'sort_order', 'name'], 'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de producto'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelManagers(
            name='stockmovement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='stocklot',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12, verbose_name='Stock mínimo sugerido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Último costo'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='kind',
            field=models.CharField(choices=[('FOOD', 'Alimentos'), ('BEVERAGE', 'Bebidas'), ('CLEANING', 'Artículos de limpieza'), ('LINEN', 'Blancos'), ('AMENITY', 'Amenidades'), ('SHOP', 'Tienda / sex shop'), ('OTHER', 'Otros')], default='OTHER', max_length=15, verbose_name='Familia'),
        ),
        migrations.AlterField(
            model_name='stocklot',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.warehouse', verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('RETURN_IN', 'Devolución de cliente'), ('TRANSFER_IN', 'Traspaso recibido'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('INITIAL', 'Inventario inicial'), ('SALE', 'Venta'), ('CONSUMPTION', 'Consumo interno'), ('WASTE', 'Merma'), ('EXPIRED', 'Caducidad'), ('TRANSFER_OUT', 'Traspaso enviado'), ('ADJUSTMENT_OUT', 'Ajuste negativo'), ('RETURN_OUT', 'Devolución a proveedor')], db_index=True, max_length=15, verbose_name='Tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='Almacén'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_default_for_sales',
            field=models.BooleanField(default=False, help_text='Del que se descuenta el room service si no se indica otro.', verbose_name='Almacén de venta por defecto'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('GENERAL', 'Almacén general'), ('KITCHEN', 'Cocina'), ('BAR', 'Bar'), ('HOUSEKEEPING', 'Ama de llaves'), ('MINIBAR', 'Frigobar / habitaciones'), ('SHOP', 'Tienda')], default='GENERAL', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='low_stock_notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Última alerta de stock'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='max_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12, verbose_name='Stock máximo'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12, verbose_name='Stock mínimo'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse', verbose_name='Almacén'),
        ),
    ]
