# Generated by Django 5.2.17 on 2026-08-18 21:38

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productcategory_options_and_more'),
        ('settings', '0006_motel_id_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('folio', models.CharField(db_index=True, editable=False, max_length=30, verbose_name='Folio')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ORDERED', 'Enviada'), ('PARTIAL', 'Recibida parcialmente'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=12, verbose_name='Estado')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de orden')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Entrega esperada')),
                ('supplier_reference', models.CharField(blank=True, max_length=60, verbose_name='Referencia del proveedor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Subtotal')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Recepción completa')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-order_date', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad solicitada')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='Cantidad recibida')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo unitario')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de impuesto')),
            ],
            options={
                'verbose_name': 'Partida de compra',
                'verbose_name_plural': 'Partidas de compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('code', models.CharField(max_length=20, verbose_name='Clave')),
                ('business_name', models.CharField(db_index=True, max_length=150, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='RFC / identificación fiscal')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=0, verbose_name='Días de crédito')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['business_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_active_product_sku',
        ),
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='uniq_active_product_category',
        ),
        migrations.RemoveConstraint(
            model_name='warehouse',
            name='uniq_active_warehouse_code',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Siempre positiva; el signo lo determina el tipo de movimiento.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('motel', 'sku'), name='uniq_active_product_sku_motel'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('motel', 'name', 'kind'), name='uniq_active_product_category_motel'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('motel', 'code'), name='uniq_active_warehouse_code_motel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse', verbose_name='Almacén destino'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='uniq_purchase_product'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='purchase_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='purchase_received_not_exceeded'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('motel', 'code'), name='uniq_active_supplier_code_motel'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-order_date'], name='purchase_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('motel', 'folio'), name='uniq_purchase_folio_motel'),
        ),
    ]
