# Generated by Django 5.2.17 on 2026-09-08 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_purchaseorderitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, help_text='Se ve en la tarjeta del punto de venta. Opcional.', upload_to='productos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Fotografia'),
        ),
    ]
