# Generated by Django 5.2.17 on 2026-08-16 06:48

import apps.users.managers
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('username', models.CharField(help_text='Clave de acceso del empleado.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Solo minusculas, numeros, punto, guion y guion bajo (3 a 40 caracteres).', regex='^[a-z0-9._-]{3,40}$')], verbose_name='Usuario')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super administrador'), ('MANAGER', 'Gerente'), ('RECEPTION', 'Recepcion'), ('HOUSEKEEPING', 'Ama de llaves')], db_index=True, default='RECEPTION', max_length=20, verbose_name='Rol')),
                ('employee_number', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numero de empleado')),
                ('hired_at', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Debe cambiar contrasena')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ultima IP')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite entrar al panel de Django.', verbose_name='Acceso al admin')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['full_name'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('username_attempted', models.CharField(blank=True, max_length=40, verbose_name='Usuario intentado')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('LOGIN_FAILED', 'Intento fallido'), ('PASSWORD_CHANGED', 'Cambio de contrasena')], max_length=20, verbose_name='Accion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Agente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad de usuario',
                'verbose_name_plural': 'Actividades de usuario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-created_at'], name='useract_user_created_idx'),
        ),
    ]
