# Generated by Django 5.2.17 on 2026-08-16 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super administrador'), ('MANAGER', 'Gerente'), ('RECEPTION', 'Recepción'), ('HOUSEKEEPING', 'Ama de llaves')], db_index=True, default='RECEPTION', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Clave de acceso del empleado.', max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='Solo minúsculas, números, punto, guion y guion bajo (3 a 40 caracteres).', regex='^[a-z0-9._-]{3,40}$')], verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento fallido'), ('PASSWORD_CHANGED', 'Cambio de contraseña')], max_length=20, verbose_name='Acción'),
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('connections', models.PositiveSmallIntegerField(default=0, verbose_name='Conexiones abiertas')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Visto por última vez')),
                ('last_section', models.CharField(blank=True, max_length=40, verbose_name='Última sección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presencia de usuario',
                'verbose_name_plural': 'Presencia de usuarios',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['-last_seen_at'], name='presence_last_seen_idx')],
            },
        ),
    ]
