# Generated by Django 5.2.17 on 2026-08-18 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('settings', '0007_motel_border_radius_motel_brand_primary_color_and_more'),
        ('users', '0003_user_motel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Clave de acceso del empleado.', max_length=40, validators=[django.core.validators.RegexValidator(message='Solo minúsculas, números, punto, guion y guion bajo (3 a 40 caracteres).', regex='^[a-z0-9._-]{3,40}$')], verbose_name='Usuario'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('motel', 'username'), name='uniq_user_username_motel'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('motel__isnull', True)), fields=('username',), name='uniq_user_username_sin_motel'),
        ),
    ]
