# Generated by Django 5.2.17 on 2026-09-07 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username_user_uniq_user_username_motel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador de sesión')),
                ('jti', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Token vigente')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Agente')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Última actividad')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Vence en')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocada en')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revocada por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['-last_seen_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='usersession_user_idx'), models.Index(fields=['revoked_at'], name='usersession_revoked_idx')],
            },
        ),
    ]
