# Generated by Django 5.2.17 on 2026-08-16 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('actor_username', models.CharField(blank=True, help_text='Se guarda aparte para que la bitacora sobreviva cambios de nombre.', max_length=40, verbose_name='Usuario (snapshot)')),
                ('action', models.CharField(choices=[('CREATE', 'Alta'), ('UPDATE', 'Modificacion'), ('SOFT_DELETE', 'Baja logica'), ('RESTORE', 'Reactivacion'), ('ROOM_RENTED', 'Renta de habitacion'), ('ROOM_EXTENDED', 'Extension de renta'), ('ROOM_CHECKOUT', 'Cierre de renta'), ('ROOM_CANCELLED', 'Cancelacion de renta'), ('ROOM_STATUS', 'Cambio de estado de habitacion'), ('ORDER_CREATED', 'Alta de consumo'), ('ORDER_CANCELLED', 'Cancelacion de consumo'), ('PAYMENT_REGISTERED', 'Registro de pago'), ('PAYMENT_VOIDED', 'Cancelacion de pago'), ('FOLIO_CLOSED', 'Cierre de cuenta'), ('SHIFT_OPENED', 'Apertura de turno'), ('SHIFT_CLOSED', 'Cierre de turno'), ('EXPENSE_REVIEWED', 'Revision de gasto'), ('STOCK_MOVED', 'Movimiento de inventario')], db_index=True, max_length=20, verbose_name='Accion')),
                ('module', models.CharField(choices=[('ROOMS', 'Recepcion'), ('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('HOUSEKEEPING', 'Ama de llaves'), ('FINANCES', 'Finanzas'), ('USERS', 'Usuarios'), ('CONFIG', 'Configuracion')], db_index=True, max_length=14, verbose_name='Modulo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=180, verbose_name='Objeto')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Formato {"campo": {"before": ..., "after": ...}}.', verbose_name='Cambios')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Agente')),
                ('actor', models.ForeignKey(blank=True, help_text='Vacio cuando la accion la ejecuta una tarea automatica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Bitacora de auditoria',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_idx'), models.Index(fields=['module', 'action', '-created_at'], name='audit_module_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_target_idx')],
            },
        ),
    ]
