# Generated by Django 5.2.17 on 2026-08-17 05:57

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('settings', '0004_alter_motel_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Bitácora de auditoría'},
        ),
        migrations.AlterModelManagers(
            name='auditlog',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Alta'), ('UPDATE', 'Modificación'), ('SOFT_DELETE', 'Baja lógica'), ('RESTORE', 'Reactivación'), ('ROOM_RENTED', 'Renta de habitación'), ('ROOM_EXTENDED', 'Extensión de renta'), ('ROOM_CHECKOUT', 'Cierre de renta'), ('ROOM_CANCELLED', 'Cancelación de renta'), ('ROOM_STATUS', 'Cambio de estado de habitación'), ('ORDER_CREATED', 'Alta de consumo'), ('ORDER_CANCELLED', 'Cancelación de consumo'), ('PAYMENT_REGISTERED', 'Registro de pago'), ('PAYMENT_VOIDED', 'Cancelación de pago'), ('FOLIO_CLOSED', 'Cierre de cuenta'), ('SHIFT_OPENED', 'Apertura de turno'), ('SHIFT_CLOSED', 'Cierre de turno'), ('EXPENSE_REVIEWED', 'Revisión de gasto'), ('STOCK_MOVED', 'Movimiento de inventario')], db_index=True, max_length=20, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Vacio cuando la acción la ejecuta una tarea automática.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor_username',
            field=models.CharField(blank=True, help_text='Se guarda aparte para que la bitácora sobreviva cambios de nombre.', max_length=40, verbose_name='Usuario (snapshot)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('ROOMS', 'Recepción'), ('SALES', 'Ventas'), ('INVENTORY', 'Inventario'), ('HOUSEKEEPING', 'Ama de llaves'), ('FINANCES', 'Finanzas'), ('USERS', 'Usuarios'), ('CONFIG', 'Configuración')], db_index=True, max_length=14, verbose_name='Modulo'),
        ),
    ]
