# Generated by Django 5.2.17 on 2026-08-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='Clave')),
                ('period_key', models.CharField(blank=True, max_length=20, verbose_name='Periodo')),
                ('prefix', models.CharField(max_length=10, verbose_name='Prefijo')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Consecutivo actual')),
                ('padding', models.PositiveSmallIntegerField(default=5, verbose_name='Digitos')),
            ],
            options={
                'verbose_name': 'Consecutivo de documento',
                'verbose_name_plural': 'Consecutivos de documento',
                'constraints': [models.UniqueConstraint(fields=('key', 'period_key'), name='uniq_document_sequence_key_period')],
            },
        ),
    ]
