# Generated by Django 5.2.17 on 2026-08-18 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_alter_maintenanceupdate_managers_cleaningtask_motel_and_more'),
        ('rooms', '0004_remove_holiday_uniq_active_holiday_date_and_more'),
        ('settings', '0007_motel_border_radius_motel_brand_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancereport',
            name='folio',
            field=models.CharField(editable=False, max_length=25, verbose_name='Folio'),
        ),
        migrations.AddConstraint(
            model_name='maintenancereport',
            constraint=models.UniqueConstraint(fields=('motel', 'folio'), name='uniq_maintenance_folio_motel'),
        ),
    ]
