# Generated by Django 5.2.17 on 2026-09-07 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0003_alter_maintenancereport_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='photo',
            field=models.FileField(blank=True, help_text='Evidencia opcional que toma quien reporta desde su telefono.', upload_to='mantenimiento/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'heic'])], verbose_name='Foto'),
        ),
    ]
