# Generated by Django 5.2.17 on 2026-08-16 07:33

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('code', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Folio de turno')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Matutino'), ('EVENING', 'Vespertino'), ('NIGHT', 'Nocturno'), ('SPECIAL', 'Especial')], default='MORNING', max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('VERIFIED', 'Verificado por gerencia')], db_index=True, default='OPEN', max_length=10, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('business_date', models.DateField(db_index=True, verbose_name='Dia de operacion')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fondo inicial')),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ventas en efectivo')),
                ('card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ventas con tarjeta')),
                ('transfer_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Transferencias')),
                ('courtesy_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cortesias')),
                ('cash_in_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Entradas de efectivo')),
                ('cash_out_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salidas de efectivo')),
                ('expenses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gastos aprobados')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Efectivo esperado')),
                ('declared_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Efectivo declarado')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Declarado menos esperado. Negativo = faltante.', max_digits=12, verbose_name='Diferencia')),
                ('folios_closed', models.PositiveIntegerField(default=0, verbose_name='Folios cerrados')),
                ('stays_closed', models.PositiveIntegerField(default=0, verbose_name='Rentas cerradas')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado en')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Turno de caja',
                'verbose_name_plural': 'Turnos de caja',
                'ordering': ['-opened_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('folio', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Folio')),
                ('category', models.CharField(choices=[('SUPPLIES', 'Insumos'), ('MAINTENANCE', 'Mantenimiento'), ('UTILITIES', 'Servicios (luz, agua, gas)'), ('PAYROLL', 'Nomina y viaticos'), ('CLEANING', 'Limpieza'), ('TRANSPORT', 'Transporte'), ('OTHER', 'Otro')], default='OTHER', max_length=12, verbose_name='Categoria')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('supplier', models.CharField(blank=True, max_length=120, verbose_name='Proveedor')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de aprobacion'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado')], db_index=True, default='APPROVED', max_length=10, verbose_name='Estado')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requiere aprobacion')),
                ('receipt_reference', models.CharField(blank=True, max_length=60, verbose_name='Comprobante')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado en')),
                ('review_notes', models.CharField(blank=True, max_length=255, verbose_name='Notas de revision')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finances.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('direction', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Sentido')),
                ('reason', models.CharField(choices=[('OPENING_FUND', 'Fondo de caja'), ('DROP', 'Retiro parcial a boveda'), ('REFILL', 'Reposicion de cambio'), ('EXPENSE', 'Gasto operativo'), ('CORRECTION', 'Correccion'), ('OTHER', 'Otro')], default='OTHER', max_length=15, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='Referencia')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='finances.expense', verbose_name='Gasto origen')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='finances.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Movimiento de efectivo',
                'verbose_name_plural': 'Movimientos de efectivo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('kind', models.CharField(choices=[('OPENING', 'Fondo inicial'), ('BLIND', 'Corte ciego'), ('DECLARED', 'Corte declarado'), ('AUDIT', 'Arqueo de gerencia')], max_length=10, verbose_name='Tipo')),
                ('breakdown', models.JSONField(default=dict, help_text='Denominacion a cantidad, p. ej. {"500": 3, "100": 12}.', verbose_name='Desglose')),
                ('declared_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total declarado')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to=settings.AUTH_USER_MODEL, verbose_name='Contado por')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_counts', to='finances.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Arqueo de caja',
                'verbose_name_plural': 'Arqueos de caja',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', '-opened_at'], name='shift_status_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['business_date'], name='shift_business_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cashier',), name='uniq_open_shift_per_cashier'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['shift', 'status'], name='expense_shift_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-created_at'], name='expense_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['shift', 'direction'], name='cashmov_shift_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='cashcount',
            index=models.Index(fields=['shift', 'kind'], name='cashcount_shift_kind_idx'),
        ),
    ]
