# Generated by Django 5.2.17 on 2026-08-17 05:57

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('settings', '0004_alter_motel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cashmovement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cashcount',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='expense',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AddField(
            model_name='shift',
            name='motel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel'),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='breakdown',
            field=models.JSONField(default=dict, help_text='Denominación a cantidad, p. ej. {"500": 3, "100": 12}.', verbose_name='Desglose'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='reason',
            field=models.CharField(choices=[('OPENING_FUND', 'Fondo de caja'), ('DROP', 'Retiro parcial a bóveda'), ('REFILL', 'Reposición de cambio'), ('EXPENSE', 'Gasto operativo'), ('CORRECTION', 'Corrección'), ('OTHER', 'Otro')], default='OTHER', max_length=15, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('SUPPLIES', 'Insumos'), ('MAINTENANCE', 'Mantenimiento'), ('UTILITIES', 'Servicios (luz, agua, gas)'), ('PAYROLL', 'Nomina y viaticos'), ('CLEANING', 'Limpieza'), ('TRANSPORT', 'Transporte'), ('OTHER', 'Otro')], default='OTHER', max_length=12, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requiere aprobación'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='review_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Notas de revisión'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de aprobación'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('CANCELLED', 'Cancelado')], db_index=True, default='APPROVED', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='business_date',
            field=models.DateField(db_index=True, verbose_name='Día de operación'),
        ),
    ]
