# Generated by Django 5.2.17 on 2026-08-16 06:48

import django.core.validators
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('code', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Folio')),
                ('folio_type', models.CharField(choices=[('ROOM', 'Cuenta de habitacion'), ('COUNTER', 'Venta de mostrador')], default='ROOM', max_length=10, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], db_index=True, default='OPEN', max_length=10, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Abierta en')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuentos')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Pagado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelacion')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'ordering': ['-opened_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('charge_type', models.CharField(choices=[('ROOM_RENT', 'Renta de habitacion'), ('EXTENSION', 'Extension de tiempo'), ('OVERSTAY', 'Recargo por tiempo excedido'), ('EXTRA_PERSON', 'Persona adicional'), ('PRODUCTS', 'Consumo de productos'), ('SERVICE', 'Servicio'), ('SURCHARGE', 'Recargo'), ('DISCOUNT', 'Descuento'), ('ADJUSTMENT', 'Ajuste')], max_length=15, verbose_name='Concepto')),
                ('description', models.CharField(max_length=180, verbose_name='Descripcion')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuesto')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positivo para cargos, negativo para descuentos.', max_digits=12, verbose_name='Importe')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelacion')),
            ],
            options={
                'verbose_name': 'Cargo del folio',
                'verbose_name_plural': 'Cargos del folio',
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('code', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Numero de orden')),
                ('order_type', models.CharField(choices=[('ROOM_SERVICE', 'Room service'), ('MINIBAR', 'Frigobar'), ('SHOP', 'Tienda / sex shop'), ('COUNTER', 'Mostrador')], default='ROOM_SERVICE', max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PLACED', 'Solicitada'), ('PREPARING', 'En preparacion'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PLACED', max_length=12, verbose_name='Estado')),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Solicitada en')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregada en')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada en')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelacion')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-placed_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('description', models.CharField(max_length=180, verbose_name='Descripcion')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=5, verbose_name='Tasa de impuesto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuesto')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Importe')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelacion')),
            ],
            options={
                'verbose_name': 'Renglon de orden',
                'verbose_name_plural': 'Renglones de orden',
                'ordering': ['id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('COURTESY', 'Cortesia')], db_index=True, max_length=10, verbose_name='Metodo')),
                ('status', models.CharField(choices=[('APPLIED', 'Aplicado'), ('VOIDED', 'Cancelado')], default='APPLIED', max_length=8, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('tendered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Efectivo recibido')),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cambio')),
                ('reference', models.CharField(blank=True, help_text='Autorizacion, ultimos 4 digitos, folio.', max_length=60, verbose_name='Referencia')),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Pagado en')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de cancelacion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-paid_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Vigente')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Desactivado en')),
                ('deletion_reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo de baja')),
                ('kind', models.CharField(choices=[('ROOM_TICKET', 'Ticket de habitacion'), ('COUNTER_TICKET', 'Ticket de mostrador'), ('ORDER_TICKET', 'Comanda'), ('SHIFT_REPORT', 'Corte de turno')], max_length=16, verbose_name='Tipo')),
                ('printer_name', models.CharField(blank=True, max_length=60, verbose_name='Impresora')),
                ('payload', models.JSONField(default=dict, verbose_name='Contenido impreso')),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='Impreso en')),
                ('copies', models.PositiveSmallIntegerField(default=1, verbose_name='Copias')),
                ('is_reprint', models.BooleanField(default=False, verbose_name='Es reimpresion')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Error de impresion')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
