# Generated by Django 5.2.17 on 2026-08-16 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('sales', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Turno en el que se cobro. Es la base del corte de caja.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finances.shift', verbose_name='Turno de caja'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['shift', 'status'], name='payment_shift_status_idx'),
        ),
    ]
