# Generated by Django 5.2.17 on 2026-09-08 15:46

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_folio_code_alter_order_code_and_more'),
        ('settings', '0007_motel_border_radius_motel_brand_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('key', models.CharField(editable=False, max_length=64, verbose_name='Clave de intento')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_attempts', to='sales.folio', verbose_name='Cuenta resultante')),
                ('motel', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='settings.motel', verbose_name='Motel')),
            ],
            options={
                'verbose_name': 'Intento de venta',
                'verbose_name_plural': 'Intentos de venta',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('motel', 'key'), name='uniq_sale_attempt_key')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
