# Generated by Django 5.2.17 on 2026-08-16 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Opcional: si se deja vacio se asigna al hacer check-in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.room', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='roomstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='roomstatuslog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='rooms.room', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.roomtype', verbose_name='Tipo de habitacion'),
        ),
        migrations.AddField(
            model_name='stay',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_stays', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por'),
        ),
        migrations.AddField(
            model_name='stay',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='stay',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='stay',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stay', to='rooms.reservation', verbose_name='Reservacion origen'),
        ),
        migrations.AddField(
            model_name='stay',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='rooms.room', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='stay',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='rooms.roomtype', verbose_name='Tipo (snapshot)'),
        ),
        migrations.AddField(
            model_name='stay',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='roomstatuslog',
            name='stay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='rooms.stay', verbose_name='Renta relacionada'),
        ),
        migrations.AddField(
            model_name='stayextension',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='stayextension',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='stayextension',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='rooms.stay', verbose_name='Renta'),
        ),
        migrations.AddField(
            model_name='stayextension',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='tariffblock',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tariffblock',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='tariffblock',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariff_blocks', to='rooms.roomtype', verbose_name='Tipo de habitacion'),
        ),
        migrations.AddField(
            model_name='tariffblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='stayextension',
            name='tariff_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='rooms.tariffblock', verbose_name='Bloque aplicado'),
        ),
        migrations.AddField(
            model_name='stay',
            name='tariff_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='rooms.tariffblock', verbose_name='Bloque tarifario'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tariff_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.tariffblock', verbose_name='Bloque tarifario'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Desactivado por'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='tariff_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rooms.tariffblock', verbose_name='Bloque tarifario'),
        ),
        migrations.AddField(
            model_name='tariffrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('date',), name='uniq_active_holiday_date'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('code',), name='uniq_active_room_type_code'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'is_active'], name='room_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='room_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('number',), name='uniq_active_room_number'),
        ),
        migrations.AddIndex(
            model_name='roomstatuslog',
            index=models.Index(fields=['room', '-created_at'], name='room_status_log_room_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstatuslog',
            index=models.Index(fields=['to_status', '-created_at'], name='room_status_log_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room_type', 'name'), name='uniq_active_tariff_block_name'),
        ),
        migrations.AddConstraint(
            model_name='tariffblock',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='tariff_block_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='stayextension',
            index=models.Index(fields=['stay', '-created_at'], name='stay_extension_stay_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['status', 'expires_at'], name='stay_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['room', 'status'], name='stay_room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['vehicle_plate'], name='stay_plate_idx'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('room',), name='uniq_active_stay_per_room'),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('check_in_at'))), name='stay_expiration_after_checkin'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'scheduled_start', 'scheduled_end'], name='reservation_window_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'scheduled_start'], name='reservation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='reservation_window_valid'),
        ),
        migrations.AddIndex(
            model_name='tariffrule',
            index=models.Index(fields=['tariff_block', 'rule_type', 'is_active'], name='tariff_rule_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffrule',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tariff_rule_date_range_valid'),
        ),
    ]
