# Generated by Django 5.2.17 on 2026-08-18 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_motel_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='border_radius',
            field=models.CharField(choices=[('square', 'Recto'), ('medium', 'Medio'), ('rounded', 'Redondeado')], default='medium', max_length=8, verbose_name='Redondeo de controles'),
        ),
        migrations.AddField(
            model_name='motel',
            name='brand_primary_color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color principal'),
        ),
        migrations.AddField(
            model_name='motel',
            name='brand_sidebar_color',
            field=models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color del menú'),
        ),
        migrations.AddField(
            model_name='motel',
            name='default_density',
            field=models.CharField(choices=[('comfortable', 'Cómoda'), ('compact', 'Compacta')], default='comfortable', max_length=12, verbose_name='Densidad predeterminada'),
        ),
        migrations.AddField(
            model_name='motel',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Del sistema')], default='light', max_length=8, verbose_name='Tema predeterminado'),
        ),
        migrations.AddField(
            model_name='motel',
            name='font_family',
            field=models.CharField(choices=[('modern', 'Moderna'), ('system', 'Del sistema'), ('rounded', 'Redondeada')], default='modern', max_length=10, verbose_name='Tipografía'),
        ),
        migrations.AddField(
            model_name='motel',
            name='login_message',
            field=models.CharField(blank=True, default='Ingresa con tu clave de empleado para continuar.', max_length=140, verbose_name='Mensaje de acceso'),
        ),
        migrations.AddField(
            model_name='motel',
            name='status_available_color',
            field=models.CharField(default='#10B981', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color disponible'),
        ),
        migrations.AddField(
            model_name='motel',
            name='status_cleaning_color',
            field=models.CharField(default='#F59E0B', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color limpieza'),
        ),
        migrations.AddField(
            model_name='motel',
            name='status_maintenance_color',
            field=models.CharField(default='#6B7280', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color mantenimiento'),
        ),
        migrations.AddField(
            model_name='motel',
            name='status_occupied_color',
            field=models.CharField(default='#EF4444', max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color hexadecimal de seis dígitos, por ejemplo #2563EB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Color ocupado'),
        ),
    ]
