# Generated by Django 5.2.17 on 2026-09-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_motel_border_radius_motel_brand_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Clave de intento')),
                ('motel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_attempts', to='settings.motel', verbose_name='Organización creada')),
            ],
            options={
                'verbose_name': 'Intento de alta',
                'verbose_name_plural': 'Intentos de alta',
            },
        ),
    ]
