# Generated by Django 5.2.17 on 2026-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_signupattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='motel',
            name='operation_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 cuartos'), ('11-30', '11-30 cuartos'), ('31-50', '31-50 cuartos'), ('50+', 'Más de 50 cuartos')], help_text='Franja de habitaciones declarada al darse de alta.', max_length=10, verbose_name='Tamaño de la operación'),
        ),
    ]
